### ISSUE TITLE
Error on console command

### ISSUE THREAD

**Issue by TonyMaster21** [TonyMaster21/skPotato#2]
When running **/potato** from console, we get the following error.

`[20:01:11 WARN]: org.bukkit.command.CommandException: Unhandled exception executing command 'potato' in plugin skPotato v0.5 BETA
[20:01:11 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[20:01:11 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[20:01:11 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[20:01:11 WARN]:        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:575)
[20:01:11 WARN]:        at ch.njol.skript.Skript.dispatchCommand(Skript.java:1084)
[20:01:11 WARN]:        at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:86)
[20:01:11 WARN]:        at ch.njol.skript.lang.Effect.run(Effect.java:54)
[20:01:11 WARN]:        at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:296)
[20:01:11 WARN]:        at ch.njol.skript.command.Commands$4$1.call(Commands.java:229)
[20:01:11 WARN]:        at ch.njol.skript.command.Commands$4$1.call(Commands.java:1)
[20:01:11 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftFuture.run(CraftFuture.java:89)
[20:01:11 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[20:01:11 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709)
[20:01:11 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[20:01:11 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[20:01:11 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[20:01:11 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:01:11 WARN]: Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R1.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
[20:01:11 WARN]:        at me.tonymaster21.skpotato.Main.onCommand(Main.java:22)
[20:01:11 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:01:11 WARN]:        ... 16 more`

_Using v0.5 BETA_

**Comment by xXAndrew28Xx** [comment]
fixed in #3

**Comment by TonyMaster21** [comment]
Closed.
